school-app-181210/force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <description>The junction object to create a many to many relationship between students and classes.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE Id #{0000}</displayFormat>
        <label>Class Enrollment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/ClassEnrollment__c/fields/ClassGrade__c.field-meta.xml
<CustomField>
    <fullName>ClassGrade__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Class Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Grade Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

school-app-181210/force-app/main/default/classes/GradeCalculationHelper.cls
public class GradeCalculationHelper {

    
    public static void updateClassGradeAverage(List<Grade__c> newGrades){
        List<Id> CeIds = new List<Id>();
        for(Grade__c gradeRecord : newGrades){
            CeIds.add(gradeRecord.Class_Enrollment__c);
        }
        AggregateResult[] aggResults = [SELECT AVG(Grade__c)average, Class_Enrollment__c
                                         FROM Grade__c
                                         WHERE Class_Enrollment__c IN :CeIds
                                         GROUP BY Class_Enrollment__c];
        
        List<ClassEnrollment__c> CEsToUpdate = new List<ClassEnrollment__c>();
        for(AggregateResult ar : aggResults){
            CEsToUpdate.add(new ClassEnrollment__c(Id = (Id)ar.get('Class_Enrollment__c'), ClassGrade__c = (Decimal)ar.get('average')));
        }
        
        update CEsToUpdate;
        
    }//end of updateClassGradeAverage method
    
    
    
}