school-app-181210/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

school-app-181210/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>Class Id #{000}</displayFormat>
        <label>Class Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <description>The junction object to create a many to many relationship between students and classes.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE Id #{0000}</displayFormat>
        <label>Class Enrollment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Grade Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

school-app-181210/force-app/main/default/classes/ClassEnrollmentTriggerHelper.cls
public class ClassEnrollmentTriggerHelper {

    public static List<Assessment__c> getAssessmentsForClasses(List<Id> classIds){
        List<Assessment__c> assessmentList = new List<Assessment__c>();
        assessmentList = [SELECT Id, Class__c 
                          FROM Assessment__c 
                          WHERE Class__c IN :classIds];
        return assessmentList;
    }
    
    public static List<ClassEnrollment__c> getCEsForClasses(List<Id> classIds){
        List<ClassEnrollment__c> ceList = new List<ClassEnrollment__c>();
        ceList = [SELECT Id, Class__c 
                          FROM ClassEnrollment__c 
                          WHERE Class__c IN :classIds];
        return ceList;
    }

    public static void createAndInsertGrades(List<Assessment__c> asmntList, List<ClassEnrollment__c> ceList){
        
        List<Grade__c> newGrades = new List<Grade__c>();
        
        for(ClassEnrollment__c ce : ceList){
            for(Assessment__c a : asmntList){
                if(ce.Class__c == a.Class__c){
                    Grade__c newG = new Grade__c();
                    newG.Class_Enrollment__c = ce.Id;
                    newG.Assessment__c = a.Id;
                    newGrades.add(newG);
                    //the below line is the same as the above 4 lines
                    //newGrades.add(new Grade__c(Class_Enrollment__c = ce.Id, Assessment__c = a.Id));
                }
            }//end of inner for loop
        }//end of outer for loop
        
        insert newGrades;
        
    }//end of createAndInsertGrades Method
    
    
}//end of helper class