school-app-181210/force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Grade Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

school-app-181210/force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

school-app-181210/force-app/main/default/classes/DuplicateChecker.cls
public class DuplicateChecker {

    public static List<Boolean> areUniqueGrades(List<Grade__c> grades){
        List<Boolean> resultsList = new List<Boolean>();
        List<Id> ceIds = new List<Id>();
        List<Id> assessmentIds = new List<Id>();
        for(Grade__c g : grades){
            ceIds.add(g.Class_Enrollment__c);
            assessmentIds.add(g.Assessment__c);
        }
        
        AggregateResult[] arList = [SELECT COUNT(Id), Class_Enrollment__c, 
                                    Assessment__c FROM Grade__c
                                    WHERE Class_Enrollment__c IN :ceIds
                                    AND Assessment__c IN :assessmentIds
                                    GROUP BY Class_Enrollment__c, Assessment__c];
        
        Integer previousSize = resultsList.size();
        for(Grade__c g : grades){
            for(AggregateResult ar : arList){
                if((Id)ar.get('Class_Enrollment__c') == g.Class_Enrollment__c
                   && (Id)ar.get('Assessment__c') == g.Assessment__c){
                       resultsList.add(False);
                       break;
                   } 
            }
            if(resultsList.size() == previousSize){
                resultsList.add(True); 
                previousSize++;
            }
			           
        }
        
        return resultsList;
    }
    
}